---
title: "EDS 220 Assignment 1 Cartography"
author: "Desik Somasundaram"
date: "9/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(spData)
library(tidyverse)
library(sf)
library(tmap)
library(here)
library(janitor)
library(spData)
library(tmaptools)
library(basemaps)
library(leaflet)
```

```{r coffee}
coffee2021 <- read.csv(here("world_coffee_july20_21.csv")) %>% 
  clean_names() %>% 
  select("name", "production_july_2020", "production_july_2021")
#file.remove("coffee-data-messy.csv")
#file.remove("data.pdf")
coffee_data = slice(d, -c(1:9)) %>% 
  select(name_long = 1, coffee_production_2020 = 2, coffee_production_2021 = 3) %>% 
  filter(!is.na(coffee_production_2020)) %>% 
  mutate_at(2:3, str_replace, " ", "") %>% 
  mutate_at(2:3, as.integer)

world_coffee = left_join(world, coffee_data)
plot(world_coffee[c("coffee_production_2020", "coffee_production_2021")])
b = c(0, 500, 1000, 2000, 3000)
```

```{r coffee}
 tm_basemap(leaflet::providers$OpenStreetMap) +
  tm_shape(world_coffee) +
  tm_fill("coffee_production_2021", title = "Thousand 60kg bags", breaks = b, textNA = "No data", colorNA = NULL) +
  tm_scale_bar() +
  tmap_mode("")
```


```{r coffee}
world_coffee <- leaflet() %>% setView(lng = -71.0589, lat = 42.3601, zoom = 12)
world_coffee %>% addTiles()
```


```{r coffee}
tm_shape(nz) +
  tm_polygons(
    "Thousand 60kg bags",
    palette = "Blues",
    n = 100,) + tm_layout(basemaps = leaflet::providers$OpenStreetMap)

tmap_mode("plot") # for an interactive version
```

```{r}
data(NLD_muni) 
osm_NLD <- read_osm(NLD_muni, ext=1.1)
tm_shape(osm_NLD) + tm_rgb()
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
